gateway:
  env: development #production
  replicaCount: 1
  image: workers_kafka-gateway
  port: 8090
  healthPort: 8091

worker:
  env: development #production
  replicaCount: 1
  image: workers_kafka-worker
  healthPort: 9091

ingress:
  host: "localhost"
  path: "/"

postgres:
  username: "postgres"
  password: "1234"
  dbName: "Tasks"

