apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels: #Labels-для селекции и группировки
        app: gateway
    spec:
      containers:
      - name: gateway
        image: {{ .Values.gateway.image }}
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: {{ .Values.gateway.port }}
        - name: health
          containerPort: 8091
        env:
          - name: ENV
            value: {{ .Values.gateway.env | quote}}
          - name: GATEWAY_HOST
            value: "0.0.0.0"
          - name: GATEWAY_PORT
            value: {{ .Values.gateway.port | quote}}

          - name: KAFKA_HOST
            value: kafka-service
          - name: KAFKA_PORT
            value: "9092"

          - name: DB_USERNAME
            value: {{ .Values.postgres.username | quote }}
          - name: DB_PASSWORD
            value: {{ .Values.postgres.password | quote }}
          - name: DB_HOST
            value: postgres-service
          - name: DB_PORT
            value: "5432"
          - name: DB_DBNAME
            value: {{ .Values.postgres.dbName | quote }}

          - name: HEALTH_HOST
            value: "0.0.0.0"
          - name: HEALTH_PORT
            value: {{ .Values.gateway.healthPort | quote}}
    

        startupProbe:
          httpGet:
            path: /live
            port: {{ .Values.gateway.healthPort }}
          failureThreshold: 10     # Даем до 10 попыток на запуск
          periodSeconds: 3        # Проверяем каждые 3 секунды
          timeoutSeconds: 2        # Ждем ответ не более 2 секунд
      
        livenessProbe:
          httpGet:
            path: /live
            port: {{ .Values.gateway.healthPort }}
          initialDelaySeconds: 5    # Даем небольшую фору после старта
          periodSeconds: 10         # Проверяем каждые 10 секунд
          timeoutSeconds: 2         # Ждем ответ не более 2 секунд
          failureThreshold: 2       # 2 неудачи подряд -> перезапуск контейнера

        readinessProbe:
          httpGet:
            path: /ready
            port: {{ .Values.gateway.healthPort }}
          initialDelaySeconds: 5
          periodSeconds: 5          # Проверяем чаще, чем liveness
          timeoutSeconds: 6         # Чуть больше таймаут, т.к. проверяет внешние зависимости
          failureThreshold: 2       # 2 неудачи -> убрать из трафика
