apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gateway-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gateway
  namespaceSelector:
    matchNames:
      - default    
  podMetricsEndpoints:
    - port: health
      path: /metrics
      interval: 5s        # Проверяем раз в 5 секунд
      scrapeTimeout: 3s   # Но если ответа нет за 3 секунды — считаем, что что-то пошло не так