FROM golang:alpine AS builder
WORKDIR /app

COPY . .
RUN go mod download

RUN go build -o main ./cmd/main.go



FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/main .
COPY --from=builder /app/config-kuber.yaml .

EXPOSE 8090
EXPOSE 8091
RUN chmod +x main
CMD ["./main", "--config", "./config-kuber.yaml"]