apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels: #Labels-для селекции и группировки
        app: worker
    spec:
      containers:
      - name: worker
        image: {{ .Values.worker.image }}
        imagePullPolicy: Never