apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels: #Labels-для селекции и группировки
        app: worker
    spec:
      containers:
      - name: worker
        image: {{ .Values.worker.image }}
        imagePullPolicy: Never
        ports:
        - name: health
          containerPort: 9091
        env:
          - name: ENV
            value: development
          - name: KAFKA_HOST
            value: kafka-service
          - name: KAFKA_PORT
            value: "9092"

          - name: HEALTH_HOST
            value: "0.0.0.0"
          - name: HEALTH_PORT
            value: "9091"